name: minesweeper_online
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # flutter_local_storage:
  #   git: https://github.com/D10100111001/flutter_local_storage
  provider: ^3.1.0
  shared_preferences: ^0.5.3+4
  audioplayers: ^0.13.2
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  assets:
    - assets/click.mp3
    - assets/opening.mp3
    - assets/flag.mp3
    - assets/win.mp3
    - assets/explode.mp3
    - assets/lose.mp3

  fonts:
    - family: Minesweeper
      fonts:
        - asset: fonts/mine-sweeper.ttf
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
        - asset: fonts/Raleway-Italic.ttf
          style: italic